CREATE TABLE PLAYER_INFO(
	PLAYER_NO NUMBER PRIMARY KEY,
	PLAYER_NAME VARCHAR(20) NOT NULL,
	PLAYER_ID VARCHAR(30) NOT NULL,
	PLAYER_PW VARCHAR(40) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN('Y','N'))
);


CREATE TABLE PLAYER_TIME(
	PLAYER_NM VARCHAR2(30) NOT NULL,
	PLAY_TIME VARCHAR2(30) NOT NULL,
	PLAY_DATE DATE DEFAULT SYSDATE
);

COMMIT;

CREATE SEQUENCE SEQ_PLAY_NO
START WITH 1
INCREMENT BY 1
NOCYCLE 
NOCACHE;

DROP TABLE PLAYER_TIME;
DROP TABLE PLAYER_INFO;

SELECT PLAYER_NM, TO_NUMBER(PLAY_TIME) , PLAY_DATE FROM PLAYER_TIME
ORDER BY TO_NUMBER(PLAY_TIME);

INSERT INTO PLAYER_TIME
VALUES(SEQ_PLAY_NO.NEXTVAL, 'onceplayer', '9.128', DEFAULT);


SELECT 순위, PLAYER_NM ,PLAY_TIME  FROM (
SELECT RANK() OVER(
 ORDER BY MAX(TO_NUMBER(PLAY_TIME))) "순위" , PLAYER_NM ,MAX(TO_NUMBER(PLAY_TIME)) PLAY_TIME
FROM PLAYER_TIME 
GROUP BY PLAYER_NM 
ORDER BY PLAY_TIME )
WHERE 순위<=10;

SELECT SYSDATE+(1/24*9) FROM DUAL;--한국시간 










SELECT ROWNUM , PLAYER_NM, PLAY_TIME, PLAY_DATE
		FROM PLAYER_TIME
		WHERE PLAYER_NM='유저이'
		AND ROWNUM<=5
		ORDER BY PLAY_DATE;
	
	SELECT AVG(PLAY_TIME) AVG_TIME
	FROM PLAYER_TIME 
	WHERE PLAYER_NM='유저이';

SELECT SYSDATE FROM DUAL;








