-- SYS 관리자 계정 

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- 사용자 계정 생성 
CREATE USER member_kys IDENTIFIED BY member1234;

-- 생성한 사용자 계정에 권한 부여 
GRANT CONNECT, RESOURCE, CREATE VIEW TO member_kys;

-- 테이블 스페이스 할당 
ALTER USER member_kys DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-- member_이니셜 계정 
-- 회원 번호, 아이디, 비밀번호, 이름, 성별, 가입일, 탈퇴여
CREATE TABLE "MEMBER"(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NM VARCHAR2(10) NOT NULL,
	MEMBER_GENDER CHAR(1) CHECK(MEMBER_GENDER IN('M','F')),
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN('Y','N'))
);

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN "MEMBER".MEMBER_GENDER IS '회원 성별';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".SECESSION_FL IS '탈퇴여부(Y/N)';

-- 회원번호 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCYCLE 
NOCACHE;


-- 회원가입 INSERT 

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER01','PASS01','유저일',
		'M', DEFAULT, DEFAULT);
	
INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER02','PASS02','유저	이',
		'M', DEFAULT, DEFAULT);
	
INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER03','PASS03','유저삼',
		'F', DEFAULT, DEFAULT);

COMMIT;


-- 아이디 중복 확인
-- (중복되는 아이디가 입력되어도 탈퇴한 계정이면 중복 X)

SELECT COUNT(*) FROM "MEMBER" 
WHERE MEMBER_ID ='user01'
AND SECESSION_FL ='N';
--> ID가 user01이면서 탈퇴하지 않은 회원 조회 

-- 중복이면 1, 아니면 0 조회 



-- 로그인 
SELECT MEMBER_NO , MEMBER_ID , MEMBER_NM ,MEMBER_GENDER,
 TO_CHAR(ENROLL_DATE,'YYYY"년" MM"월" DD"일" HH24:MI:SS')
 FROM "MEMBER"
WHERE MEMBER_ID='user05'
AND MEMBER_PW ='pass05'
AND SECESSION_FL ='N'; 




UPDATE "MEMBER" SET
MEMBER_PW ='새 비밀번호'
WHERE MEMBER_NO =1
AND MEMBER_PW ='현재 비밀버u'


-- 회원 탈퇴(SECESSION_FL칼럼 값을 Y로 변)
UPDATE "MEMBER" SET
SECESSION_FL ='Y'
WHERE MEMBER_NO=?
AND MEMBER_PW=?








